### ISSUE TITLE
Remove Inline Styles from our ACF Blocks

### ISSUE THREAD

**Issue by coreymcollins** [WebDevStudios/wd_s#408] opened 2018-10-04 20:20 UTC
A general plan of attack:
- Stop using the ACF color picker and instead use a filtered & styled select dropdown with defined colors. We already define colors and hide the color picker, so why not just go the next step and stop using the color picker all together? This would also eliminate the need for admin JS.
- This allows us to set class names for colors (`background-green`, `color-green`, etc.) and use those instead of inline styles
- Videos are already not inline, so I think we're good there
- Instead of using images as inline background styles, use a `<figure>` element to place them inside of the container and position the same way we're doing with "background" videos

This would get us away from adding inline styles to our blocks at all, as everything would either be handled by a class (background colors, text colors) or inline elements positioned as background elements (videos, images).

**Comment by sarthak0906** [comment] 2018-10-11 14:52
Is the issue still open is it closed
If the issue is still open, I'll like to take up the task

**Comment by coreymcollins** [comment] 2018-10-11 15:08
@sarthak0906 – this has already been worked on and PR'd, but thanks for checking!

**Comment by gregrickaby** [comment] 2018-10-19 14:10
Closing per #409

**Closed as completed by gregrickaby** 2018-10-19 14:10 UTC
Labels: hacktoberfest, r4r, enhancement
